# Regression using an Artificial Neural Network

A simple ANN regression model built using the ['Combined Cycle Power Plant'](https://archive.ics.uci.edu/dataset/294/combined+cycle+power+plant) dataset from the UC Irvine Machine Learning Repository, and as part of a [Udemy course](https://www.udemy.com/course/linear-regression-with-artificial-neural-network/learn/lecture/18888982#overview) on building a regression model with an ANN. The dataset consists of 9568 data points collected from a Combined Cycle Power Plant. Features are as follows.
- Temperature (T) in the range 1.81°C and 37.11°C,
- Ambient Pressure (AP) in the range 992.89-1033.30 milibar,
- Relative Humidity (RH) in the range 25.56% to 100.16%
- Exhaust Vacuum (V) in the range 25.36-81.56 cm Hg
- Net hourly electrical energy output (EP) 420.26-495.76 MW

This model attempts to predict hourly electrical output given the Temperature, Ambient Pressure, Relative Humidity and Exhaust Vacuum.

<br></br>
***
## Libraries

In [9]:
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error

<br></br>
***
## Data Preprocessing

### **Import**

In [10]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [11]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


<br></br>
### **Split the dataset into training and test sets**

In [12]:
# test_size: Sets the size of the test set to 20% of the original dataset
# random_state: Sets randomisation of the splitting process to zero, ensuring that the data is always split in the same way
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

<br></br>
***
## Building the ANN

In [13]:
ann = tf.keras.models.Sequential()
# Input and 1st layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Second layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Output layer
# Note: No activation function on the output neuron, as the output should be a continuous real number
ann.add(tf.keras.layers.Dense(units=1))

# 'adam' : Optimizer used during back propagation. Better than SGD as it adapts the learning rate, and uses momentum to navigate steep/shallow gradients
# 'mean_squared_error' : Loss function which penalises predictions that are further away from the actual value more than those that are closer
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

<br></br>
***
## Training the ANN

In [14]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 849us/step - loss: 12358.4990
Epoch 2/100
240/240 [==============================] - 0s 824us/step - loss: 195.5432
Epoch 3/100
240/240 [==============================] - 0s 816us/step - loss: 186.9117
Epoch 4/100
240/240 [==============================] - 0s 812us/step - loss: 176.0876
Epoch 5/100
240/240 [==============================] - 0s 806us/step - loss: 163.9512
Epoch 6/100
240/240 [==============================] - 0s 796us/step - loss: 151.3801
Epoch 7/100
240/240 [==============================] - 0s 791us/step - loss: 137.6919
Epoch 8/100
240/240 [==============================] - 0s 785us/step - loss: 124.6469
Epoch 9/100
240/240 [==============================] - 0s 776us/step - loss: 111.5338
Epoch 10/100
240/240 [==============================] - 0s 783us/step - loss: 99.5052
Epoch 11/100
240/240 [==============================] - 0s 786us/step - loss: 88.6133
Epoch 12/100
240/240 [==============================

<br></br>
***
## Predictions using the ANN

In [15]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 679us/step
[[430.79 431.23]
 [461.83 460.01]
 [465.33 461.14]
 ...
 [472.59 473.26]
 [439.31 438.  ]
 [458.56 463.28]]


<br></br>
***
## Determining ANN Accuracy

In [16]:
# Calculate Mean Squared Error (MSE)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error (MSE):", mse)

# Calculate Mean Absolute Error (MAE)
mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error (MAE):", mae)

Mean Squared Error (MSE): 24.81889039765765
Mean Absolute Error (MAE): 3.940058547192357
